// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gyMs0bWpfUXjWyH_IskZpq_EkJLbC-4',
    appId: '1:94140168394:web:0c413c9eff8ddb7db15c33',
    messagingSenderId: '94140168394',
    projectId: 'phone-auth-5d21d',
    authDomain: 'phone-auth-5d21d.firebaseapp.com',
    storageBucket: 'phone-auth-5d21d.appspot.com',
    measurementId: 'G-QL0B3671YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyVcaM0fOzPcYLeLPzWUm2umfBBs1tdl4',
    appId: '1:94140168394:android:6df8db44d9ab8d14b15c33',
    messagingSenderId: '94140168394',
    projectId: 'phone-auth-5d21d',
    storageBucket: 'phone-auth-5d21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjW4hmWv6bgGmjOLcxRkNevGBFGaS0pcg',
    appId: '1:94140168394:ios:33bb539dd60bceddb15c33',
    messagingSenderId: '94140168394',
    projectId: 'phone-auth-5d21d',
    storageBucket: 'phone-auth-5d21d.appspot.com',
    androidClientId: '94140168394-72ijdq2sdprlc3v2nqfam07jhv3stq50.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjW4hmWv6bgGmjOLcxRkNevGBFGaS0pcg',
    appId: '1:94140168394:ios:33bb539dd60bceddb15c33',
    messagingSenderId: '94140168394',
    projectId: 'phone-auth-5d21d',
    storageBucket: 'phone-auth-5d21d.appspot.com',
    androidClientId: '94140168394-72ijdq2sdprlc3v2nqfam07jhv3stq50.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1gyMs0bWpfUXjWyH_IskZpq_EkJLbC-4',
    appId: '1:94140168394:web:55cce326fa6cba85b15c33',
    messagingSenderId: '94140168394',
    projectId: 'phone-auth-5d21d',
    authDomain: 'phone-auth-5d21d.firebaseapp.com',
    storageBucket: 'phone-auth-5d21d.appspot.com',
    measurementId: 'G-4P4WMMS6HW',
  );
}
